# Generated by Django 3.2.6 on 2021-08-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=15, verbose_name='Код')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Наименование')),
                ('level_1', models.CharField(blank=True, max_length=50, verbose_name='Уровень 1')),
                ('level_2', models.CharField(blank=True, max_length=50, verbose_name='Уровень 2')),
                ('level_3', models.CharField(blank=True, max_length=50, verbose_name='Уровень 3')),
                ('price', models.DecimalField(decimal_places=5, max_digits=10, null=True, verbose_name='Цена')),
                ('price_sp', models.DecimalField(decimal_places=5, max_digits=10, null=True, verbose_name='Цена СП')),
                ('amount', models.IntegerField(null=True, verbose_name='Количество')),
                ('fields_of_options', models.TextField(blank=True, verbose_name='Поля свойств')),
                ('joint_purchases', models.IntegerField(null=True, verbose_name='Совместные покупки')),
                ('unit', models.CharField(blank=True, max_length=15, verbose_name='Единица измерения')),
                ('image', models.CharField(blank=True, max_length=100, verbose_name='Картинка')),
                ('show_on_main_page', models.BooleanField(blank=True, verbose_name='Выводить на главной')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'CSVObject',
                'verbose_name_plural': 'CSVObjects',
            },
        ),
    ]
