# Generated by Django 3.2.6 on 2021-08-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvobject',
            name='show_on_main_page',
            field=models.IntegerField(blank=True, null=True, verbose_name='Выводить на главной'),
        ),
    ]
